version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.11.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: 'yarn install'
      - run:
          name: Run Tests
          command: 'yarn ci:test'

