version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.11.0
    steps:
      - checkout
      - run:
          name: Install npm
          command: 'sudo npm install -g npm@6.11.3'
      - run:
          name: Install dependencies
          command: 'npm install'
      - run:
          name: Run Tests
          command: 'npm test'

